import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { BellRing, CalendarDays, FilePenLine, Loader2, ScanText, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

const toLocalInput = (timestamp: number | null | undefined) => timestamp ? new Date(timestamp - new Date().getTimezoneOffset() * 60_000).toISOString().slice(0, 16) : "";

export default function AdminSchemes() {
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const schemesQuery = trpc.admin.schemes.list.useQuery(undefined, { enabled: user?.role === "admin" });
  const automation = trpc.admin.documentAutomation.status.useQuery(undefined, { enabled: user?.role === "admin" });
  const ocrPolicy = trpc.admin.ocrPolicy.get.useQuery(undefined, { enabled: user?.role === "admin" });
  const [selectedId, setSelectedId] = useState("");
  const selected = schemesQuery.data?.schemes.find((scheme) => scheme.id === selectedId) ?? schemesQuery.data?.schemes[0];
  const [draft, setDraft] = useState({ name: "", nameHindi: "", administeringBody: "", benefits: "", benefitsHindi: "", portalUrl: "", deadline: "", deadlineLabel: "", reviewed: "" });
  useEffect(() => { if (selected) { setSelectedId(selected.id); setDraft({ name: selected.name, nameHindi: selected.nameHindi, administeringBody: selected.administeringBody, benefits: selected.benefits, benefitsHindi: selected.benefitsHindi, portalUrl: selected.portalUrl, deadline: toLocalInput(selected.applicationDeadline), deadlineLabel: selected.deadlineLabel ?? "", reviewed: selected.reviewed }); } }, [selected?.id]);
  const update = trpc.admin.schemes.update.useMutation({ onSuccess: async () => { await utils.admin.schemes.list.invalidate(); await utils.schemes.list.invalidate(); toast.success("Scheme information updated."); }, onError: (error) => toast.error(error.message || "The scheme could not be updated.") });
  const enableAutomation = trpc.admin.documentAutomation.enable.useMutation({ onSuccess: async () => { await utils.admin.documentAutomation.status.invalidate(); toast.success("Daily document expiry scan enabled."); }, onError: () => toast.error("Publish the project before enabling the live daily scan.") });
  const updateOcrPolicy = trpc.admin.ocrPolicy.update.useMutation({ onSuccess: async () => { await utils.admin.ocrPolicy.get.invalidate(); await utils.applications.list.invalidate(); toast.success("OCR review threshold updated."); }, onError: () => toast.error("The OCR review threshold could not be updated.") });
  if (user?.role !== "admin") return <DashboardLayout><div className="admin-denied"><ShieldCheck size={28} /><h1>Administrator access required</h1><p>This workspace is available to Scheme Sathi administrators only.</p></div></DashboardLayout>;

  return <DashboardLayout><div className="admin-schemes"><header className="desk-masthead"><div><span className="desk-kicker"><ShieldCheck size={14} /> ADMINISTRATION</span><h1>Keep scheme guidance <em>current.</em></h1><p>Update official links, benefit copy, review notes and application deadline details without touching user records.</p></div></header>
    <section className="admin-control-grid"><section className="admin-automation-card"><div><span className="desk-kicker"><BellRing size={14} /> DOCUMENT AUTOMATION</span><h2>Daily expiry scan</h2><p>{automation.data?.setting?.scheduleCronTaskUid ? "The daily document expiry scan is enabled for the production site." : "The daily scan is ready in code. Publish first, then enable it to create the live Heartbeat job."}</p></div><button className="desk-outline" disabled={!!automation.data?.setting?.scheduleCronTaskUid || enableAutomation.isPending} onClick={() => enableAutomation.mutate()}>{enableAutomation.isPending ? <Loader2 className="spin" size={15} /> : <BellRing size={15} />}{automation.data?.setting?.scheduleCronTaskUid ? "Daily scan active" : "Enable after publish"}</button></section>
      <section className="admin-policy-card"><div><span className="desk-kicker"><ScanText size={14} /> OCR REVIEW POLICY</span><h2>Flag manual review below</h2><p>Documents with concerns are always flagged. This setting controls the lowest accepted AI confidence for a clear badge.</p></div><div className="policy-options">{(["low", "medium", "high"] as const).map((confidence) => <button key={confidence} className={ocrPolicy.data?.policy.minimumConfidence === confidence ? "active" : ""} disabled={updateOcrPolicy.isPending} onClick={() => updateOcrPolicy.mutate({ minimumConfidence: confidence })}><strong>{confidence}</strong><span>{confidence === "low" ? "Few flags" : confidence === "medium" ? "Balanced" : "Strict"}</span></button>)}</div></section>
    </section>
    <section className="admin-editor"><aside className="admin-scheme-list"><span className="desk-kicker">CATALOGUE</span>{schemesQuery.isLoading && <Loader2 className="spin" />}{schemesQuery.data?.schemes.map((scheme) => <button key={scheme.id} className={selected?.id === scheme.id ? "active" : ""} onClick={() => setSelectedId(scheme.id)}><span>{scheme.category}</span><strong>{scheme.name}</strong></button>)}</aside>{selected && <form className="admin-form" onSubmit={(event) => { event.preventDefault(); update.mutate({ schemeId: selected.id, name: draft.name, nameHindi: draft.nameHindi, administeringBody: draft.administeringBody, benefits: draft.benefits, benefitsHindi: draft.benefitsHindi, portalUrl: draft.portalUrl, applicationDeadline: draft.deadline ? new Date(draft.deadline).getTime() : null, deadlineLabel: draft.deadlineLabel || null, reviewed: draft.reviewed }); }}><div className="admin-form-heading"><div><span className="desk-kicker"><FilePenLine size={14} /> EDIT SCHEME</span><h2>{selected.name}</h2></div><button className="desk-primary" disabled={update.isPending}>{update.isPending ? <Loader2 className="spin" size={15} /> : <FilePenLine size={15} />} Save changes</button></div><div className="admin-form-grid"><label>Scheme name<input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label><label>Hindi scheme name<input value={draft.nameHindi} onChange={(event) => setDraft({ ...draft, nameHindi: event.target.value })} /></label><label>Administering body<input value={draft.administeringBody} onChange={(event) => setDraft({ ...draft, administeringBody: event.target.value })} /></label><label>Official portal URL<input type="url" value={draft.portalUrl} onChange={(event) => setDraft({ ...draft, portalUrl: event.target.value })} /></label><label className="full">Benefit summary<textarea value={draft.benefits} onChange={(event) => setDraft({ ...draft, benefits: event.target.value })} /></label><label className="full">Benefit summary — Hindi<textarea value={draft.benefitsHindi} onChange={(event) => setDraft({ ...draft, benefitsHindi: event.target.value })} /></label></div><div className="admin-deadline-box"><span><CalendarDays size={18} /></span><div><strong>Application timing</strong><p>Leave the date blank when the official application window is not announced.</p></div><label>Deadline<input type="datetime-local" value={draft.deadline} onChange={(event) => setDraft({ ...draft, deadline: event.target.value })} /></label><label>Deadline label<input value={draft.deadlineLabel} placeholder="e.g. Applications close 31 Oct 2026" onChange={(event) => setDraft({ ...draft, deadlineLabel: event.target.value })} /></label><label>Review note<input value={draft.reviewed} onChange={(event) => setDraft({ ...draft, reviewed: event.target.value })} /></label></div></form>}</section></div></DashboardLayout>;
}
