/* Scheme Sathi backend contract: bilingual catalog content and eligibility rules live in one server-safe source. */

export type SchemeLevel = "Central" | "State";

export type EligibilityRule = {
  ageMin?: number;
  ageMax?: number;
  incomeMax?: number;
  casteCategories?: string[] | "all";
  occupations?: string[] | "all";
  states?: string[] | "all";
  genders?: string[] | "all";
  requiresStudent?: boolean;
  requiresFarmer?: boolean;
  requiresDisability?: boolean;
};

export type SchemeCatalogItem = {
  id: string;
  name: string;
  nameHindi: string;
  category: string;
  categoryHindi: string;
  level: SchemeLevel;
  administeringBody: string;
  benefits: string;
  benefitsHindi: string;
  eligibility: EligibilityRule;
  documents: string[];
  documentsHindi: string[];
  steps: string[];
  stepsHindi: string[];
  portalUrl: string;
  sourceUrl?: string | null;
  verificationStatus?: "officialDirectory" | "eligibilityVerified" | "officialNotice";
  reviewed: string;
  accent: "saffron" | "emerald" | "coral" | "indigo";
  artwork: string;
  applicationDeadline?: number | null;
  deadlineLabel?: string | null;
};

export type SchemeProfileInput = {
  age: number;
  state: string;
  caste: string;
  annualIncome: number;
  occupation: string;
  gender: string;
  isStudent: boolean;
  isFarmer: boolean;
  isDisabled: boolean;
};

const artwork = {
  farmer: "/manus-storage/scheme-sathi-farmer_fa6fb4ad.png",
  education: "/manus-storage/scheme-sathi-education_87d604a6.png",
  health: "/manus-storage/scheme-sathi-health_7a34a071.png",
};

const nspDirectoryUrl = "https://scholarships.gov.in/All-Scholarships";
const directoryDocuments = ["Official scheme specification", "Student / institution details if requested", "Portal-requested category, state or disability proof"];
const directoryDocumentsHindi = ["आधिकारिक योजना विनिर्देश", "मांगे जाने पर छात्र / संस्थान विवरण", "पोर्टल द्वारा मांगा गया वर्ग, राज्य या दिव्यांगता प्रमाण"];
const directorySteps = ["Open the official NSP scheme directory", "Read the current specification and application status", "Apply only after confirming every official requirement"];
const directoryStepsHindi = ["आधिकारिक एनएसपी योजना निर्देशिका खोलें", "वर्तमान विनिर्देश और आवेदन स्थिति पढ़ें", "हर आधिकारिक शर्त की पुष्टि के बाद ही आवेदन करें"];

type DirectoryScholarship = Pick<SchemeCatalogItem, "id" | "name" | "nameHindi" | "administeringBody"> & {
  eligibility?: EligibilityRule;
};

const officialDirectoryScholarships: SchemeCatalogItem[] = ([
  { id: "aicte-swanath-degree", name: "AICTE Swanath Scholarship Scheme (Technical Degree)", nameHindi: "एआईसीटीई स्वनाथ छात्रवृत्ति योजना (तकनीकी डिग्री)", administeringBody: "All India Council for Technical Education" },
  { id: "pmusp-jkl", name: "PM USP Special Scholarship Scheme for Jammu Kashmir and Ladakh", nameHindi: "जम्मू, कश्मीर और लद्दाख के लिए पीएम यूएसपी विशेष छात्रवृत्ति योजना", administeringBody: "All India Council for Technical Education", eligibility: { states: ["Jammu and Kashmir", "Ladakh"] } },
  { id: "aicte-pragati-degree", name: "AICTE Pragati Scholarship Scheme for Girl Students (Technical Degree)", nameHindi: "एआईसीटीई प्रगति छात्रवृत्ति योजना (छात्राएँ, तकनीकी डिग्री)", administeringBody: "All India Council for Technical Education", eligibility: { genders: ["Female"] } },
  { id: "aicte-pragati-diploma", name: "AICTE Pragati Scholarship Scheme for Girl Students (Technical Diploma)", nameHindi: "एआईसीटीई प्रगति छात्रवृत्ति योजना (छात्राएँ, तकनीकी डिप्लोमा)", administeringBody: "All India Council for Technical Education", eligibility: { genders: ["Female"] } },
  { id: "aicte-saksham-diploma", name: "AICTE Saksham Scholarship Scheme for Specially Abled Student (Technical Diploma)", nameHindi: "एआईसीटीई सक्षम छात्रवृत्ति योजना (दिव्यांग छात्र, तकनीकी डिप्लोमा)", administeringBody: "All India Council for Technical Education", eligibility: { requiresDisability: true } },
  { id: "aicte-saksham-degree", name: "AICTE Saksham Scholarship Scheme for Specially Abled Student (Technical Degree)", nameHindi: "एआईसीटीई सक्षम छात्रवृत्ति योजना (दिव्यांग छात्र, तकनीकी डिग्री)", administeringBody: "All India Council for Technical Education", eligibility: { requiresDisability: true } },
  { id: "aicte-swanath-diploma", name: "AICTE Swanath Scholarship Scheme (Technical Diploma)", nameHindi: "एआईसीटीई स्वनाथ छात्रवृत्ति योजना (तकनीकी डिप्लोमा)", administeringBody: "All India Council for Technical Education" },
  { id: "ugc-postgraduate", name: "National Scholarship for Post Graduate Studies", nameHindi: "स्नातकोत्तर अध्ययन के लिए राष्ट्रीय छात्रवृत्ति", administeringBody: "University Grants Commission" },
  { id: "ugc-ishan-uday", name: "Ishan Uday Special Scholarship Scheme for NER", nameHindi: "पूर्वोत्तर क्षेत्र के लिए ईशान उदय विशेष छात्रवृत्ति योजना", administeringBody: "University Grants Commission", eligibility: { states: ["Arunachal Pradesh", "Assam", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Sikkim", "Tripura"] } },
  { id: "mha-police-wards", name: "Prime Minister's Scholarship Scheme for Wards of States/UTs Police Personnel Martyred During Terror/Naxal Attacks", nameHindi: "शहीद राज्य/केंद्रशासित प्रदेश पुलिसकर्मियों के आश्रितों के लिए प्रधानमंत्री छात्रवृत्ति योजना", administeringBody: "Ministry of Home Affairs" },
  { id: "mha-capf-assam-rifles", name: "Prime Minister's Scholarship Scheme for Central Armed Police Forces and Assam Rifles", nameHindi: "केंद्रीय सशस्त्र पुलिस बल और असम राइफल्स के लिए प्रधानमंत्री छात्रवृत्ति योजना", administeringBody: "Ministry of Home Affairs" },
  { id: "labour-beedi-postmatric", name: "Financial Assistance for Education to the Wards of Beedi/Cine/IOMC/LSDM — Post Matric", nameHindi: "बीड़ी/सिने/आईओएमसी/एलएसडीएम कर्मियों के आश्रितों के लिए शिक्षा सहायता — पोस्ट मैट्रिक", administeringBody: "Ministry of Labour & Employment" },
  { id: "labour-beedi-prematric", name: "Financial Assistance for Education to the Wards of Beedi/Cine/IOMC/LSDM — Pre Matric", nameHindi: "बीड़ी/सिने/आईओएमसी/एलएसडीएम कर्मियों के आश्रितों के लिए शिक्षा सहायता — प्री मैट्रिक", administeringBody: "Ministry of Labour & Employment" },
  { id: "yasasvi-school", name: "PM YASASVI Central Sector Scheme of Top Class Education in Schools for OBC, EBC and DNT Students", nameHindi: "ओबीसी, ईबीसी और डीएनटी विद्यार्थियों के लिए पीएम यशस्वी स्कूल शिक्षा छात्रवृत्ति", administeringBody: "Department of Social Justice & Empowerment (Backward Classes)" },
  { id: "yasasvi-college", name: "PM YASASVI Central Sector Scheme of Top Class Education in College for OBC, EBC and DNT Students", nameHindi: "ओबीसी, ईबीसी और डीएनटी विद्यार्थियों के लिए पीएम यशस्वी कॉलेज शिक्षा छात्रवृत्ति", administeringBody: "Department of Social Justice & Empowerment (Backward Classes)" },
  { id: "mnre-fellowship", name: "National Renewable Energy Fellowship Scheme", nameHindi: "राष्ट्रीय नवीकरणीय ऊर्जा फेलोशिप योजना", administeringBody: "Ministry of New and Renewable Energy" },
  { id: "mospi-isi-stipend", name: "Stipend Scheme for Undergraduate and Postgraduate Studies in Indian Statistical Institute, Kolkata", nameHindi: "भारतीय सांख्यिकी संस्थान, कोलकाता में स्नातक और स्नातकोत्तर अध्ययन के लिए स्टाइपेंड योजना", administeringBody: "Ministry of Statistics and Programme Implementation" },
  { id: "icar-nts-ug", name: "ICAR National Talent Scholarship (NTS-UG)", nameHindi: "आईसीएआर राष्ट्रीय प्रतिभा छात्रवृत्ति (एनटीएस-यूजी)", administeringBody: "Department of Agriculture Research and Education" },
  { id: "icar-pgs", name: "ICAR Post Graduate Scholarship (PGS)", nameHindi: "आईसीएआर स्नातकोत्तर छात्रवृत्ति (पीजीएस)", administeringBody: "Department of Agriculture Research and Education" },
  { id: "icar-nts-pg", name: "ICAR National Talent Scholarship (NTS-PG)", nameHindi: "आईसीएआर राष्ट्रीय प्रतिभा छात्रवृत्ति (एनटीएस-पीजी)", administeringBody: "Department of Agriculture Research and Education" },
  { id: "icar-jrf-srf", name: "ICAR Junior Research Fellowships (JRF) and Senior Research Fellowships (SRF)", nameHindi: "आईसीएआर जूनियर और सीनियर रिसर्च फेलोशिप", administeringBody: "Department of Agriculture Research and Education" },
  { id: "sc-top-class", name: "Central Sector Scholarship of Top Class Education for SC Students", nameHindi: "एससी विद्यार्थियों के लिए टॉप क्लास शिक्षा केंद्रीय छात्रवृत्ति", administeringBody: "Department of Social Justice & Empowerment" },
  { id: "sc-obc-coaching", name: "Free Coaching for SCs, OBCs and Beneficiaries of PM CARES Children Scheme", nameHindi: "एससी, ओबीसी और पीएम केयर्स बाल योजना लाभार्थियों के लिए निःशुल्क कोचिंग", administeringBody: "Department of Social Justice & Empowerment" },
  { id: "disability-prematric", name: "Pre Matric Scholarship for Students with Disabilities", nameHindi: "दिव्यांग विद्यार्थियों के लिए प्री मैट्रिक छात्रवृत्ति", administeringBody: "Department of Empowerment of Persons with Disabilities", eligibility: { requiresDisability: true } },
  { id: "disability-postmatric", name: "Post Matric Scholarship for Students with Disabilities", nameHindi: "दिव्यांग विद्यार्थियों के लिए पोस्ट मैट्रिक छात्रवृत्ति", administeringBody: "Department of Empowerment of Persons with Disabilities", eligibility: { requiresDisability: true } },
  { id: "disability-top-class", name: "Scholarship for Top Class Education for Students with Disabilities", nameHindi: "दिव्यांग विद्यार्थियों के लिए टॉप क्लास शिक्षा छात्रवृत्ति", administeringBody: "Department of Empowerment of Persons with Disabilities", eligibility: { requiresDisability: true } },
  { id: "nmmss", name: "National Means Cum Merit Scholarship", nameHindi: "राष्ट्रीय साधन-सह-योग्यता छात्रवृत्ति", administeringBody: "Department of School Education & Literacy" },
  { id: "pmusp-csss", name: "PM-USP Central Sector Scheme of Scholarship for College and University Students (CSSS)", nameHindi: "कॉलेज और विश्वविद्यालय विद्यार्थियों के लिए पीएम-यूएसपी केंद्रीय क्षेत्र छात्रवृत्ति योजना", administeringBody: "Department of Higher Education" },
  { id: "tribal-top-class", name: "National Fellowship and Scholarship for Higher Education of ST Students — Scholarship", nameHindi: "एसटी विद्यार्थियों की उच्च शिक्षा के लिए राष्ट्रीय फेलोशिप और छात्रवृत्ति", administeringBody: "Ministry of Tribal Affairs" },
  { id: "nec-merit", name: "Financial Support to the Students of NER for Higher Professional Courses (NEC Merit Scholarship)", nameHindi: "उच्च व्यावसायिक पाठ्यक्रमों के लिए एनईआर विद्यार्थियों को वित्तीय सहायता (एनईसी मेरिट छात्रवृत्ति)", administeringBody: "North Eastern Council, DoNER" },
  { id: "railway-pmss", name: "Prime Minister's Scholarship Scheme for Ministry of Railways", nameHindi: "रेल मंत्रालय के लिए प्रधानमंत्री छात्रवृत्ति योजना", administeringBody: "Ministry of Railways" },
] satisfies DirectoryScholarship[]).map(item => ({
  ...item,
  category: "Education",
  categoryHindi: "शिक्षा",
  level: "Central",
  benefits: "Listed in the official National Scholarship Portal directory. Read the current official specification to confirm benefit amount, course, institution and application terms.",
  benefitsHindi: "आधिकारिक राष्ट्रीय छात्रवृत्ति पोर्टल निर्देशिका में सूचीबद्ध। लाभ राशि, पाठ्यक्रम, संस्थान और आवेदन शर्तों की पुष्टि के लिए वर्तमान आधिकारिक विनिर्देश पढ़ें।",
  eligibility: { ageMin: 10, ageMax: 45, casteCategories: "all", occupations: "all", states: "all", requiresStudent: true, ...item.eligibility },
  documents: directoryDocuments,
  documentsHindi: directoryDocumentsHindi,
  steps: directorySteps,
  stepsHindi: directoryStepsHindi,
  portalUrl: nspDirectoryUrl,
  sourceUrl: nspDirectoryUrl,
  verificationStatus: "officialDirectory",
  reviewed: "Official NSP directory checked 19 Aug 2026",
  accent: "indigo",
  artwork: artwork.education,
}));

export const schemeCatalog: SchemeCatalogItem[] = [
  { id: "pmjay", name: "Ayushman Bharat PM-JAY", nameHindi: "आयुष्मान भारत प्रधानमंत्री जन आरोग्य योजना", category: "Health", categoryHindi: "स्वास्थ्य", level: "Central", administeringBody: "National Health Authority", benefits: "Cashless health cover up to ₹5 lakh per family per year at empanelled hospitals.", benefitsHindi: "सूचीबद्ध अस्पतालों में प्रति परिवार प्रति वर्ष ₹5 लाख तक का कैशलेस स्वास्थ्य कवर।", eligibility: { ageMin: 0, incomeMax: 300000, casteCategories: "all", occupations: "all", states: "all" }, documents: ["Aadhaar or alternate ID", "Ration card / family ID", "Mobile number"], documentsHindi: ["आधार या वैकल्पिक पहचान पत्र", "राशन कार्ड / परिवार आईडी", "मोबाइल नंबर"], steps: ["Check your name in the beneficiary list", "Visit a CSC or empanelled hospital", "Carry your ID and complete e-KYC"], stepsHindi: ["लाभार्थी सूची में अपना नाम देखें", "सीएससी या सूचीबद्ध अस्पताल जाएँ", "पहचान पत्र लेकर ई-केवाईसी पूरा करें"], portalUrl: "https://pmjay.gov.in/", reviewed: "Reviewed 18 Jun 2026", accent: "emerald", artwork: artwork.health },
  { id: "pmkisan", name: "PM-KISAN Samman Nidhi", nameHindi: "प्रधानमंत्री किसान सम्मान निधि", category: "Agriculture", categoryHindi: "कृषि", level: "Central", administeringBody: "Department of Agriculture & Farmers Welfare", benefits: "Income support of ₹6,000 per year for eligible landholding farmers.", benefitsHindi: "पात्र भूमिधारक किसानों को हर साल ₹6,000 की आय सहायता।", eligibility: { ageMin: 18, casteCategories: "all", occupations: ["Farmer", "Agriculture"], states: "all", requiresFarmer: true }, documents: ["Aadhaar card", "Land ownership record", "Bank account details"], documentsHindi: ["आधार कार्ड", "भूमि स्वामित्व रिकॉर्ड", "बैंक खाते का विवरण"], steps: ["Open the PM-KISAN portal", "Complete farmer registration with land details", "Finish Aadhaar-linked e-KYC"], stepsHindi: ["पीएम-किसान पोर्टल खोलें", "भूमि विवरण के साथ किसान पंजीकरण करें", "आधार से जुड़ी ई-केवाईसी पूरी करें"], portalUrl: "https://pmkisan.gov.in/", reviewed: "Reviewed 12 Jun 2026", accent: "saffron", artwork: artwork.farmer },
  { id: "pmfby", name: "Pradhan Mantri Fasal Bima Yojana", nameHindi: "प्रधानमंत्री फसल बीमा योजना", category: "Agriculture", categoryHindi: "कृषि", level: "Central", administeringBody: "Ministry of Agriculture & Farmers Welfare", benefits: "Affordable crop insurance against natural risks, pests and diseases for notified crops.", benefitsHindi: "अधिसूचित फसलों के लिए प्राकृतिक जोखिम, कीट और रोगों से किफायती फसल बीमा।", eligibility: { ageMin: 18, occupations: ["Farmer", "Agriculture"], states: "all", requiresFarmer: true }, documents: ["Aadhaar card", "Land or tenancy record", "Sowing declaration and bank details"], documentsHindi: ["आधार कार्ड", "भूमि या किरायेदारी रिकॉर्ड", "बुवाई घोषणा और बैंक विवरण"], steps: ["Check the notified crop and season", "Apply through a bank, CSC or the portal", "Keep the acknowledgement for claim support"], stepsHindi: ["अधिसूचित फसल और मौसम देखें", "बैंक, सीएससी या पोर्टल से आवेदन करें", "दावे के लिए पावती सुरक्षित रखें"], portalUrl: "https://pmfby.gov.in/", reviewed: "Reviewed 09 Jun 2026", accent: "saffron", artwork: artwork.farmer },
  { id: "nsp", name: "National Scholarship Portal", nameHindi: "राष्ट्रीय छात्रवृत्ति पोर्टल", category: "Education", categoryHindi: "शिक्षा", level: "Central", administeringBody: "Ministry of Education", benefits: "One-window access to multiple pre-matric, post-matric and merit scholarships.", benefitsHindi: "प्री-मैट्रिक, पोस्ट-मैट्रिक और मेरिट छात्रवृत्तियों तक एक ही जगह से पहुँच।", eligibility: { ageMin: 10, ageMax: 35, incomeMax: 800000, casteCategories: "all", occupations: "all", states: "all", requiresStudent: true }, documents: ["Student ID and Aadhaar", "Income certificate", "Previous marksheet and bank details"], documentsHindi: ["छात्र आईडी और आधार", "आय प्रमाण पत्र", "पिछली अंकतालिका और बैंक विवरण"], steps: ["Create a student profile on NSP", "Select the scholarship that fits your course", "Submit documents through your institute"], stepsHindi: ["एनएसपी पर छात्र प्रोफाइल बनाएँ", "अपने पाठ्यक्रम के लिए छात्रवृत्ति चुनें", "संस्थान के माध्यम से दस्तावेज जमा करें"], portalUrl: "https://scholarships.gov.in/", reviewed: "Reviewed 04 Jun 2026", accent: "indigo", artwork: artwork.education, applicationDeadline: Date.UTC(2026, 9, 31, 18, 29, 59), deadlineLabel: "Student applications close 31 Oct 2026" },
  { id: "pmuy", name: "Pradhan Mantri Ujjwala Yojana", nameHindi: "प्रधानमंत्री उज्ज्वला योजना", category: "Women & Family", categoryHindi: "महिला एवं परिवार", level: "Central", administeringBody: "Ministry of Petroleum & Natural Gas", benefits: "Deposit-free LPG connection support for eligible adult women from low-income households.", benefitsHindi: "कम आय वाले परिवारों की पात्र वयस्क महिलाओं के लिए जमा-रहित एलपीजी कनेक्शन सहायता।", eligibility: { ageMin: 18, incomeMax: 300000, genders: ["Female"], states: "all" }, documents: ["Aadhaar of applicant and adult family members", "Address proof", "Bank account details"], documentsHindi: ["आवेदक और वयस्क परिवार सदस्यों का आधार", "पता प्रमाण", "बैंक खाते का विवरण"], steps: ["Visit an LPG distributor", "Submit KYC and household declaration", "Collect connection details after verification"], stepsHindi: ["एलपीजी वितरक के पास जाएँ", "केवाईसी और परिवार घोषणा जमा करें", "सत्यापन के बाद कनेक्शन विवरण प्राप्त करें"], portalUrl: "https://www.pmuy.gov.in/", reviewed: "Reviewed 27 May 2026", accent: "coral", artwork: artwork.health },
  { id: "pmsvanidhi", name: "PM SVANidhi", nameHindi: "पीएम स्वनिधि", category: "Livelihood", categoryHindi: "आजीविका", level: "Central", administeringBody: "Ministry of Housing & Urban Affairs", benefits: "Collateral-free working capital support with incentives for street vendors who repay on time.", benefitsHindi: "समय पर भुगतान करने वाले स्ट्रीट वेंडर्स के लिए बिना गारंटी कार्यशील पूंजी सहायता और प्रोत्साहन।", eligibility: { ageMin: 18, occupations: ["Street Vendor", "Small Business", "Business Owner", "Self-Employed"], states: "all" }, documents: ["Certificate of vending or local survey record", "Aadhaar card", "Bank account and mobile number"], documentsHindi: ["वेंडिंग प्रमाण पत्र या स्थानीय सर्वे रिकॉर्ड", "आधार कार्ड", "बैंक खाता और मोबाइल नंबर"], steps: ["Contact your urban local body or lending partner", "Submit vendor verification details", "Track loan and digital cashback incentives"], stepsHindi: ["शहरी स्थानीय निकाय या ऋण भागीदार से संपर्क करें", "वेंडर सत्यापन विवरण जमा करें", "ऋण और डिजिटल कैशबैक प्रोत्साहन ट्रैक करें"], portalUrl: "https://pmsvanidhi.mohua.gov.in/", reviewed: "Reviewed 22 May 2026", accent: "saffron", artwork: artwork.farmer },
  { id: "standup-india", name: "Stand-Up India", nameHindi: "स्टैंड-अप इंडिया", category: "Enterprise", categoryHindi: "उद्यमिता", level: "Central", administeringBody: "Department of Financial Services", benefits: "Bank loans for greenfield enterprises promoted by women or SC/ST entrepreneurs.", benefitsHindi: "महिला या एससी/एसटी उद्यमियों द्वारा शुरू किए गए नए उद्यमों के लिए बैंक ऋण।", eligibility: { ageMin: 18, casteCategories: ["SC", "ST", "all"], occupations: ["Entrepreneur", "Business Owner", "Self-Employed"], states: "all", genders: ["Female", "all"] }, documents: ["Identity and address proof", "Business plan", "Caste or woman entrepreneur proof where applicable"], documentsHindi: ["पहचान और पता प्रमाण", "व्यवसाय योजना", "लागू होने पर जाति या महिला उद्यमी प्रमाण"], steps: ["Prepare a viable greenfield business plan", "Apply through the portal or bank branch", "Complete lender due diligence"], stepsHindi: ["व्यवहार्य नए व्यवसाय की योजना बनाएँ", "पोर्टल या बैंक शाखा से आवेदन करें", "ऋणदाता की जाँच पूरी करें"], portalUrl: "https://www.standupmitra.in/", reviewed: "Reviewed 16 May 2026", accent: "coral", artwork: artwork.education },
  { id: "pmay-urban", name: "PMAY — Urban Housing", nameHindi: "प्रधानमंत्री आवास योजना — शहरी", category: "Housing", categoryHindi: "आवास", level: "Central", administeringBody: "Ministry of Housing & Urban Affairs", benefits: "Support for eligible urban families to build, buy or improve a pucca home.", benefitsHindi: "पात्र शहरी परिवारों को पक्का घर बनाने, खरीदने या सुधारने में सहायता।", eligibility: { ageMin: 18, incomeMax: 1800000, states: "all" }, documents: ["Identity and address proof", "Income certificate", "Land or property documents if applicable"], documentsHindi: ["पहचान और पता प्रमाण", "आय प्रमाण पत्र", "लागू होने पर भूमि या संपत्ति दस्तावेज"], steps: ["Check the housing vertical available in your city", "Apply through the local body or official portal", "Track verification and sanction status"], stepsHindi: ["अपने शहर में उपलब्ध आवास विकल्प देखें", "स्थानीय निकाय या आधिकारिक पोर्टल से आवेदन करें", "सत्यापन और स्वीकृति स्थिति ट्रैक करें"], portalUrl: "https://pmay-urban.gov.in/", reviewed: "Reviewed 10 May 2026", accent: "indigo", artwork: artwork.health },
  { id: "nsap", name: "National Social Assistance Programme", nameHindi: "राष्ट्रीय सामाजिक सहायता कार्यक्रम", category: "Social Security", categoryHindi: "सामाजिक सुरक्षा", level: "Central", administeringBody: "Ministry of Rural Development", benefits: "Social assistance pensions for eligible elderly persons, widows and persons with disabilities.", benefitsHindi: "पात्र बुजुर्गों, विधवाओं और दिव्यांग व्यक्तियों के लिए सामाजिक सहायता पेंशन।", eligibility: { ageMin: 18, incomeMax: 300000, states: "all", requiresDisability: true }, documents: ["Age or disability proof", "Aadhaar or alternate ID", "Bank or post-office account"], documentsHindi: ["आयु या दिव्यांगता प्रमाण", "आधार या वैकल्पिक पहचान पत्र", "बैंक या डाकघर खाता"], steps: ["Contact your Gram Panchayat or municipal office", "Submit the pension application", "Keep acknowledgement for status checks"], stepsHindi: ["ग्राम पंचायत या नगर कार्यालय से संपर्क करें", "पेंशन आवेदन जमा करें", "स्थिति जाँच के लिए पावती रखें"], portalUrl: "https://nsap.nic.in/", reviewed: "Reviewed 03 May 2026", accent: "emerald", artwork: artwork.health },
  { id: "up-kanya", name: "Mukhyamantri Kanya Sumangala", nameHindi: "मुख्यमंत्री कन्या सुमंगला योजना", category: "Women & Family", categoryHindi: "महिला एवं परिवार", level: "State", administeringBody: "Government of Uttar Pradesh", benefits: "Stage-wise financial support for the health, education and development of a girl child in Uttar Pradesh.", benefitsHindi: "उत्तर प्रदेश में बालिका के स्वास्थ्य, शिक्षा और विकास के लिए चरणबद्ध आर्थिक सहायता।", eligibility: { ageMin: 0, ageMax: 25, incomeMax: 300000, genders: ["Female"], states: ["Uttar Pradesh"] }, documents: ["UP residence proof", "Girl child birth certificate", "Family income certificate and bank details"], documentsHindi: ["उत्तर प्रदेश निवास प्रमाण", "बालिका का जन्म प्रमाण पत्र", "परिवार आय प्रमाण और बैंक विवरण"], steps: ["Register on the state portal", "Upload stage-specific documents", "Track approval and instalment status"], stepsHindi: ["राज्य पोर्टल पर पंजीकरण करें", "चरण के अनुसार दस्तावेज अपलोड करें", "स्वीकृति और किस्त की स्थिति ट्रैक करें"], portalUrl: "https://mksy.up.gov.in/", reviewed: "Reviewed 18 Apr 2026", accent: "coral", artwork: artwork.education },
  { id: "maha-ladki", name: "Majhi Ladki Bahin Yojana", nameHindi: "मुख्यमंत्री माझी लाडकी बहिन योजना", category: "Women & Family", categoryHindi: "महिला एवं परिवार", level: "State", administeringBody: "Government of Maharashtra", benefits: "Direct support for eligible women residents of Maharashtra, subject to current state criteria.", benefitsHindi: "वर्तमान राज्य मानदंडों के अधीन महाराष्ट्र की पात्र महिला निवासियों के लिए प्रत्यक्ष सहायता।", eligibility: { ageMin: 21, ageMax: 65, incomeMax: 250000, genders: ["Female"], states: ["Maharashtra"] }, documents: ["Maharashtra residence proof", "Aadhaar-linked mobile", "Bank account and income declaration"], documentsHindi: ["महाराष्ट्र निवास प्रमाण", "आधार से जुड़ा मोबाइल", "बैंक खाता और आय घोषणा"], steps: ["Use the official state application channel", "Complete identity and bank verification", "Check the current notice before applying"], stepsHindi: ["आधिकारिक राज्य आवेदन माध्यम का उपयोग करें", "पहचान और बैंक सत्यापन पूरा करें", "आवेदन से पहले वर्तमान सरकारी सूचना देखें"], portalUrl: "https://ladakibahin.maharashtra.gov.in/", reviewed: "Reviewed 11 Apr 2026", accent: "saffron", artwork: artwork.health },
  { id: "pmddky", name: "PM Dhan-Dhaanya Krishi Yojana", nameHindi: "प्रधानमंत्री धन-धान्य कृषि योजना", category: "Agriculture", categoryHindi: "कृषि", level: "Central", administeringBody: "Ministry of Agriculture & Farmers Welfare", benefits: "Priority delivery of 36 central schemes — farm credit, crop insurance, irrigation and storage support — for farmers in 100 selected agricultural districts over six years from 2025-26.", benefitsHindi: "100 चयनित कृषि जिलों के किसानों के लिए 36 केंद्रीय योजनाओं — कृषि ऋण, फसल बीमा, सिंचाई और भंडारण सहायता — की प्राथमिकता से डिलीवरी, 2025-26 से छह वर्षों तक।", eligibility: { ageMin: 18, casteCategories: "all", occupations: ["Farmer", "Agriculture"], states: "all", requiresFarmer: true }, documents: ["Aadhaar card", "Land ownership record", "Bank account details"], documentsHindi: ["आधार कार्ड", "भूमि स्वामित्व रिकॉर्ड", "बैंक खाते का विवरण"], steps: ["Check whether your district is among the 100 selected districts", "Contact your district agriculture office or Dhan-Dhaanya Samiti", "Apply to the relevant underlying scheme through its normal process"], stepsHindi: ["जाँचें कि आपका जिला 100 चयनित जिलों में है या नहीं", "जिला कृषि कार्यालय या धन-धान्य समिति से संपर्क करें", "संबंधित मूल योजना में सामान्य प्रक्रिया से आवेदन करें"], portalUrl: "https://pmddky.niti.gov.in/", sourceUrl: "https://pmddky.niti.gov.in/", verificationStatus: "officialNotice", reviewed: "Official portal checked 17 Sep 2026", accent: "saffron", artwork: artwork.farmer },
  { id: "dalhan-mission", name: "Pulse Self-Reliance Mission (Dalhan Atmanirbharta Mission)", nameHindi: "दलहन आत्मनिर्भरता मिशन", category: "Agriculture", categoryHindi: "कृषि", level: "Central", administeringBody: "Ministry of Agriculture & Farmers Welfare", benefits: "Production assistance and assured procurement support for pulse-growing farmers under the national pulse self-reliance push launched in October 2025.", benefitsHindi: "अक्टूबर 2025 में शुरू राष्ट्रीय दलहन आत्मनिर्भरता अभियान के तहत दलहन उगाने वाले किसानों के लिए उत्पादन सहायता और सुनिश्चित खरीद सहायता।", eligibility: { ageMin: 18, casteCategories: "all", occupations: ["Farmer", "Agriculture"], states: "all", requiresFarmer: true }, documents: ["Aadhaar card", "Land ownership record", "Bank account details"], documentsHindi: ["आधार कार्ड", "भूमि स्वामित्व रिकॉर्ड", "बैंक खाते का विवरण"], steps: ["Contact your district agriculture office for mission guidelines", "Register your pulse crop and sowing details", "Follow the official procurement announcements"], stepsHindi: ["मिशन दिशानिर्देशों के लिए जिला कृषि कार्यालय से संपर्क करें", "अपनी दलहन फसल और बुवाई का विवरण दर्ज कराएँ", "आधिकारिक खरीद घोषणाओं का पालन करें"], portalUrl: "https://agriwelfare.gov.in/", sourceUrl: "https://agriwelfare.gov.in/", verificationStatus: "officialNotice", reviewed: "Official portal checked 17 Sep 2026", accent: "saffron", artwork: artwork.farmer },
  { id: "gobardhan-cbg", name: "GOBARdhan — National Circular Bioenergy Scheme", nameHindi: "गोबर्धन — राष्ट्रीय सर्कुलर जैव ऊर्जा योजना", category: "Agriculture", categoryHindi: "कृषि", level: "Central", administeringBody: "Ministry of Petroleum & Natural Gas", benefits: "Capital assistance, assured offtake and pipeline connectivity for compressed biogas plants, plus biomass supply opportunities for farmers. Scheme outlay ₹23,731 crore for FY 2026-27 to FY 2035-36.", benefitsHindi: "कंप्रेस्ड बायोगैस संयंत्रों के लिए पूंजी सहायता, सुनिश्चित खरीद और पाइपलाइन कनेक्टिविटी, साथ ही किसानों के लिए बायोमास आपूर्ति के अवसर। वित्त वर्ष 2026-27 से 2035-36 तक ₹23,731 करोड़ का योजना परिव्यय।", eligibility: { ageMin: 18, casteCategories: "all", occupations: ["Farmer", "Agriculture", "Entrepreneur", "Self-Employed", "Business Owner"], states: "all" }, documents: ["Aadhaar card", "Land or plant site record", "Bank account details"], documentsHindi: ["आधार कार्ड", "भूमि या संयंत्र स्थल रिकॉर्ड", "बैंक खाते का विवरण"], steps: ["Open the GOBARdhan portal and read the scheme components", "Check the Biomass Aggregation or pipeline support that fits you", "Apply through the official channel and track status"], stepsHindi: ["गोबर्धन पोर्टल खोलें और योजना घटक पढ़ें", "आपके लिए उपयुक्त बायोमास या पाइपलाइन सहायता देखें", "आधिकारिक माध्यम से आवेदन करें और स्थिति ट्रैक करें"], portalUrl: "https://gobardhan.gov.in/", sourceUrl: "https://gobardhan.gov.in/", verificationStatus: "officialNotice", reviewed: "Official portal checked 17 Sep 2026", accent: "saffron", artwork: artwork.farmer },
  { id: "png-domestic-incentive", name: "Incentive Scheme for Domestic PNG Connections", nameHindi: "घरेलू पीएनजी कनेक्शन प्रोत्साहन योजना", category: "Women & Family", categoryHindi: "महिला एवं परिवार", level: "Central", administeringBody: "Ministry of Petroleum & Natural Gas", benefits: "Support for households taking piped natural gas connections as city gas networks expand, effective 1 September 2026. Check the unified registration portal or your local gas distributor.", benefitsHindi: "शहरी गैस नेटवर्क के विस्तार के साथ पाइप्ड प्राकृतिक गैस कनेक्शन लेने वाले परिवारों के लिए सहायता, 1 सितंबर 2026 से प्रभावी। एकीकृत पंजीकरण पोर्टल या स्थानीय गैस वितरक से जाँचें।", eligibility: { ageMin: 18, casteCategories: "all", states: "all" }, documents: ["Address proof", "Identity proof", "Contact and bank details where requested"], documentsHindi: ["पता प्रमाण", "पहचान प्रमाण", "मांगे जाने पर संपर्क और बैंक विवरण"], steps: ["Contact your local city gas distributor", "Register for a new PNG connection", "Track installation and billing status"], stepsHindi: ["स्थानीय शहरी गैस वितरक से संपर्क करें", "नए पीएनजी कनेक्शन के लिए पंजीकरण करें", "स्थापना और बिलिंग स्थिति ट्रैक करें"], portalUrl: "https://www.pngrb.gov.in/", sourceUrl: "https://www.pngrb.gov.in/", verificationStatus: "officialNotice", reviewed: "Official portal checked 17 Sep 2026", accent: "coral", artwork: artwork.health },
  ...officialDirectoryScholarships,
];
