import { trpc } from "@/lib/trpc";
import { BadgeCheck, CheckSquare, Loader2, ScanText, ShieldCheck, Square } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

export function BatchOcrReview() {
  const utils = trpc.useUtils();
  const applications = trpc.applications.list.useQuery();
  const [selected, setSelected] = useState<number[]>([]);
  const documents = useMemo(() => (applications.data?.applications ?? []).flatMap((application) => (application.documents ?? []).map((document) => ({ ...document, schemeName: application.scheme?.name ?? application.schemeId }))), [applications.data]);
  const select = (documentId: number) => setSelected((current) => current.includes(documentId) ? current.filter((id) => id !== documentId) : [...current, documentId]);
  const batchExtract = trpc.documents.batchExtract.useMutation({ onSuccess: async ({ outcomes }) => { await utils.applications.list.invalidate(); const failed = outcomes.filter((outcome) => !outcome.ok).length; toast.success(`${outcomes.length - failed} document${outcomes.length - failed === 1 ? "" : "s"} sent for OCR${failed ? `; ${failed} need retry.` : "."}`); }, onError: () => toast.error("Batch OCR could not be started.") });
  const batchApprove = trpc.documents.batchApproveOcr.useMutation({ onSuccess: async ({ outcomes }) => { await utils.applications.list.invalidate(); const failed = outcomes.filter((outcome) => !outcome.ok).length; toast.success(`${outcomes.length - failed} document${outcomes.length - failed === 1 ? "" : "s"} approved${failed ? `; ${failed} still need review.` : "."}`); }, onError: () => toast.error("Batch approval could not be completed.") });
  const extractable = selected.filter((id) => documents.find((document) => document.id === id)?.ocrStatus !== "processing");
  const approvable = selected.filter((id) => { const document = documents.find((candidate) => candidate.id === id); return document?.ocrStatus === "complete" && !document.userVerifiedAt; });

  if (!documents.length) return null;
  return <section className="batch-ocr-review"><div className="batch-heading"><div><span className="desk-kicker"><CheckSquare size={14} /> BATCH REVIEW</span><h2>Review several documents, carefully.</h2><p>Select up to 5 files for OCR at once. Batch approval only confirms completed OCR results; you remain responsible for checking each preview.</p></div><span>{selected.length} selected</span></div><div className="batch-document-list">{documents.map((document) => <label className={selected.includes(document.id) ? "selected" : ""} key={document.id}><button type="button" onClick={() => select(document.id)} aria-pressed={selected.includes(document.id)}>{selected.includes(document.id) ? <CheckSquare size={17} /> : <Square size={17} />}</button><div><strong>{document.documentName}</strong><small>{document.fileName} · {document.schemeName}</small></div><span className={`batch-doc-status ${document.ocrStatus}`}>{document.userVerifiedAt ? "Verified" : document.ocrStatus === "complete" ? "Ready to review" : document.ocrStatus === "failed" ? "Needs retry" : document.ocrStatus === "processing" ? "Extracting" : "OCR pending"}</span></label>)}</div><div className="batch-actions"><div><ShieldCheck size={15} /><span>Batch actions preserve per-document results. Unsuccessful files remain available for individual retry.</span></div><button className="desk-outline" disabled={!extractable.length || extractable.length > 5 || batchExtract.isPending} onClick={() => batchExtract.mutate({ documentIds: extractable.slice(0, 5) })}>{batchExtract.isPending ? <Loader2 className="spin" size={15} /> : <ScanText size={15} />} Run OCR for {extractable.length || "selected"}</button><button className="desk-primary" disabled={!approvable.length || batchApprove.isPending} onClick={() => batchApprove.mutate({ documentIds: approvable })}>{batchApprove.isPending ? <Loader2 className="spin" size={15} /> : <BadgeCheck size={15} />} Approve {approvable.length || "selected"}</button></div>{extractable.length > 5 && <small className="batch-limit">Select no more than 5 documents for one OCR batch.</small>}</section>;
}
