import { FileText, ImageOff, Loader2 } from "lucide-react";
import { thumbnailFeedback } from "@/lib/verificationHistory";
import { clampPdfPage, clampPdfZoom, findPdfHighlightRects, findPdfTextMatches, nextPdfRotation, type PdfHighlightRect } from "@/lib/pdfPreview";
import { useEffect, useState } from "react";
import "./DocumentThumbnail.css";

type ThumbnailState = { status: "loading" | "ready" | "unavailable"; src?: string; pageCount?: number; renderedPage?: number; pageWidth?: number; pageHeight?: number };
type PdfTextItem = { str?: string; transform?: number[]; width?: number; height?: number };
type PdfLoadingTask = { promise: Promise<{ numPages: number; getPage(pageNumber: number): Promise<{ getViewport(options: { scale: number }): { width: number; height: number }; render(options: { canvasContext: CanvasRenderingContext2D; viewport: unknown }): { promise: Promise<void> }; getTextContent(): Promise<{ items: PdfTextItem[] }> }>; destroy(): Promise<void> }>; destroy?: () => Promise<void> | void };
type CachedPage = { src: string; pageWidth: number; pageHeight: number };
const pdfThumbnailCache = new Map<string, CachedPage>();

export function DocumentThumbnail({ url, mimeType, fileName, className = "", scale = 0.34, showNavigation = scale >= 0.7, onPageChange }: { url: string; mimeType: string; fileName: string; className?: string; scale?: number; showNavigation?: boolean; onPageChange?: (pageNumber: number, pageCount: number) => void }) {
  const [state, setState] = useState<ThumbnailState>(() => mimeType === "application/pdf" ? { status: "loading" } : { status: "ready", src: url }); const [pageNumber, setPageNumber] = useState(1); const [zoom, setZoom] = useState(1); const [rotation, setRotation] = useState(0); const [searchQuery, setSearchQuery] = useState(""); const [searchMatches, setSearchMatches] = useState<{ pageNumber: number; count: number }[]>([]); const [highlights, setHighlights] = useState<Record<number, PdfHighlightRect[]>>({}); const [searching, setSearching] = useState(false); const renderScale = scale * zoom;
  useEffect(() => { setPageNumber(1); setZoom(1); setRotation(0); setSearchQuery(""); setSearchMatches([]); setHighlights({}); }, [url]);
  useEffect(() => { if (mimeType !== "application/pdf") { setState({ status: "ready", src: url }); return; } const cacheKey = `${url}:${renderScale}:${pageNumber}`; const cached = pdfThumbnailCache.get(cacheKey); if (cached) { setState((current) => ({ status: "ready", src: cached.src, pageCount: current.pageCount, renderedPage: pageNumber, pageWidth: cached.pageWidth, pageHeight: cached.pageHeight })); return; } let active = true; let loadingTask: PdfLoadingTask | undefined; setState({ status: "loading" }); void (async () => { try { const pdfjs = await import("pdfjs-dist/build/pdf.mjs"); pdfjs.GlobalWorkerOptions.workerSrc = new URL("pdfjs-dist/build/pdf.worker.min.mjs", import.meta.url).toString(); const task = pdfjs.getDocument({ url, isEvalSupported: false }) as PdfLoadingTask; loadingTask = task; const pdf = await task.promise; const renderedPage = clampPdfPage(pageNumber, pdf.numPages); const page = await pdf.getPage(renderedPage); const viewport = page.getViewport({ scale: renderScale }); const canvas = document.createElement("canvas"); canvas.width = Math.max(1, Math.floor(viewport.width)); canvas.height = Math.max(1, Math.floor(viewport.height)); const context = canvas.getContext("2d"); if (!context) throw new Error("Canvas preview is unavailable"); await page.render({ canvasContext: context, viewport }).promise; const src = canvas.toDataURL("image/jpeg", 0.78); pdfThumbnailCache.set(cacheKey, { src, pageWidth: viewport.width, pageHeight: viewport.height }); if (active) setState({ status: "ready", src, pageCount: pdf.numPages, renderedPage, pageWidth: viewport.width, pageHeight: viewport.height }); await pdf.destroy(); } catch { if (active) setState({ status: "unavailable" }); } })(); return () => { active = false; void loadingTask?.destroy?.(); }; }, [mimeType, pageNumber, renderScale, url]);
  useEffect(() => { if (mimeType === "application/pdf" && showNavigation && state.status === "ready" && state.pageCount) onPageChange?.(state.renderedPage ?? pageNumber, state.pageCount); }, [mimeType, onPageChange, pageNumber, showNavigation, state.pageCount, state.renderedPage, state.status]);
  if (state.status === "loading") return <div className={`document-thumbnail loading ${className}`}><Loader2 className="spin" size={16} /><span>{thumbnailFeedback("loading")}</span></div>;
  if (state.status === "unavailable") return <div className={`document-thumbnail unavailable ${className}`}><ImageOff size={17} /><span>{thumbnailFeedback("unavailable")}</span></div>;
  const page = state.renderedPage ?? pageNumber; const pageHighlights = highlights[page] ?? []; const image = <div className="document-pdf-surface"><div className="document-pdf-page-box" style={{ aspectRatio: `${state.pageWidth ?? 1}/${state.pageHeight ?? 1}`, transform: `scale(${zoom}) rotate(${rotation}deg)` }}><img className="document-thumbnail image" src={state.src} alt={`Page ${page} preview of ${fileName}`} />{pageHighlights.length > 0 && <span className="pdf-highlight-layer" aria-label={`${pageHighlights.length} highlighted match${pageHighlights.length === 1 ? "" : "es"} on this page`}>{pageHighlights.map((highlight, index) => <i key={index} style={{ left: `${highlight.left}%`, top: `${highlight.top}%`, width: `${highlight.width}%`, height: `${highlight.height}%` }} />)}</span>}</div></div>;
  if (!showNavigation || mimeType !== "application/pdf" || !state.pageCount) return <span className={className}>{mimeType === "application/pdf" ? image : <img className="document-thumbnail image" src={state.src} alt={`Preview of ${fileName}`} />}</span>;
  const search = async () => { const query = searchQuery.trim(); if (!query) { setSearchMatches([]); setHighlights({}); return; } setSearching(true); try { const pdfjs = await import("pdfjs-dist/build/pdf.mjs"); pdfjs.GlobalWorkerOptions.workerSrc = new URL("pdfjs-dist/build/pdf.worker.min.mjs", import.meta.url).toString(); const task = pdfjs.getDocument({ url, isEvalSupported: false }) as PdfLoadingTask; const pdf = await task.promise; const pages = []; const nextHighlights: Record<number, PdfHighlightRect[]> = {}; for (let index = 1; index <= Math.min(pdf.numPages, 40); index += 1) { const pdfPage = await pdf.getPage(index); const viewport = pdfPage.getViewport({ scale: 1 }); const content = await pdfPage.getTextContent(); pages.push({ pageNumber: index, text: content.items.map((item) => item.str ?? "").join(" ") }); nextHighlights[index] = findPdfHighlightRects(content.items, query, viewport.width, viewport.height); } const matches = findPdfTextMatches(pages, query); setSearchMatches(matches); setHighlights(nextHighlights); if (matches[0]) setPageNumber(matches[0].pageNumber); await pdf.destroy(); } catch { setSearchMatches([]); setHighlights({}); } finally { setSearching(false); } };
  const totalMatches = searchMatches.reduce((total, match) => total + match.count, 0);
  return <div className={`document-thumbnail-paged ${className}`}>{image}<nav aria-label="PDF page navigation"><button type="button" disabled={page <= 1} onClick={() => setPageNumber((current) => clampPdfPage(current - 1, state.pageCount ?? 1))}>Previous</button><span>Page {page} of {state.pageCount}</span><button type="button" disabled={page >= state.pageCount} onClick={() => setPageNumber((current) => clampPdfPage(current + 1, state.pageCount ?? 1))}>Next</button></nav><div className="document-preview-transforms" aria-label="PDF readability controls"><button type="button" disabled={zoom <= 0.7} onClick={() => setZoom((current) => clampPdfZoom(current - 0.15))}>− Zoom</button><span>{Math.round(zoom * 100)}%</span><button type="button" disabled={zoom >= 2} onClick={() => setZoom((current) => clampPdfZoom(current + 0.15))}>+ Zoom</button><button type="button" onClick={() => setRotation(nextPdfRotation)}>Rotate</button><button type="button" disabled={zoom === 1 && rotation === 0} onClick={() => { setZoom(1); setRotation(0); }}>Reset</button></div><div className="document-preview-search"><label>Find in PDF<input value={searchQuery} maxLength={120} placeholder="Keyword or phrase" onChange={(event) => setSearchQuery(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); void search(); } }} /></label><button type="button" disabled={searching || !searchQuery.trim()} onClick={() => void search()}>{searching ? "Searching…" : "Find"}</button>{searchQuery.trim() && !searching && <small>{totalMatches ? `${totalMatches} match${totalMatches === 1 ? "" : "es"} across ${searchMatches.length} page${searchMatches.length === 1 ? "" : "s"}. Highlighted words appear in saffron.` : "No matches in the first 40 pages."}</small>}{searchMatches.length > 0 && <span>{searchMatches.map((match) => <button type="button" key={match.pageNumber} onClick={() => setPageNumber(match.pageNumber)}>Page {match.pageNumber} ({match.count})</button>)}</span>}</div></div>;
}
export function DocumentThumbnailPlaceholder() { return <div className="document-thumbnail unavailable"><FileText size={17} /><span>Document preview</span></div>; }
