import type { ReceivedVerificationHistoryFilterInvite, SavedVerificationHistoryFilter, SharedVerificationHistoryFilter, VerificationHistoryFilterShareRecipient } from "@shared/verificationHistoryFilters";
import { trpc } from "@/lib/trpc";
import { Check, Loader2, MailCheck, Share2, UsersRound, X } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import "./FamilyFilterShare.css";

type ApplicableFilter = SavedVerificationHistoryFilter | SharedVerificationHistoryFilter["filter"];

export function FamilyFilterShare({ filters, shares, received, invitations, onApply }: { filters: SavedVerificationHistoryFilter[]; shares: VerificationHistoryFilterShareRecipient[]; received: SharedVerificationHistoryFilter[]; invitations?: ReceivedVerificationHistoryFilterInvite[]; onApply: (filter: ApplicableFilter) => void }) {
  const utils = trpc.useUtils(); const [recipientEmail, setRecipientEmail] = useState(""); const [filterId, setFilterId] = useState<number | null>(filters[0]?.id ?? null);
  const invitationInbox = trpc.documents.historyFilters.list.useQuery(undefined, { enabled: invitations === undefined, staleTime: 10_000 }); const activeInvitations = invitations ?? invitationInbox.data?.invitations ?? [];
  const namedShares = useMemo(() => shares.map((share) => ({ ...share, filterName: filters.find((filter) => filter.id === share.savedFilterId)?.name ?? "Deleted filter" })), [filters, shares]);
  const refresh = () => utils.documents.historyFilters.list.invalidate();
  const share = trpc.documents.historyFilters.share.useMutation({ onSuccess: async () => { setRecipientEmail(""); await refresh(); toast.success("Family invitation sent for approval."); }, onError: (error) => toast.error(error.message || "This filter invitation could not be sent.") });
  const revoke = trpc.documents.historyFilters.revokeShare.useMutation({ onSuccess: refresh, onError: () => toast.error("Family invitation or access could not be revoked.") });
  const respond = trpc.documents.historyFilters.respondToInvite.useMutation({ onSuccess: async ({ invitation }) => { await refresh(); toast.success(invitation.status === "accepted" ? "Family filter invitation accepted." : "Family filter invitation declined."); }, onError: (error) => toast.error(error.message || "This invitation could not be updated.") });
  return <section className="family-filter-share"><div><span className="desk-kicker"><UsersRound size={14} /> FAMILY FILTERS</span><p>Send a saved criteria set for approval. It never shares documents, activity, applications, or default view access.</p></div><div className="family-share-form"><select value={filterId ?? ""} onChange={(event) => setFilterId(Number(event.target.value))} aria-label="Saved filter to invite family" disabled={!filters.length}><option value="" disabled>Select a saved filter</option>{filters.map((filter) => <option key={filter.id} value={filter.id}>{filter.name}</option>)}</select><input type="email" value={recipientEmail} placeholder="Family account email" aria-label="Family account email" onChange={(event) => setRecipientEmail(event.target.value)} /><button type="button" className="desk-outline" disabled={!filterId || !recipientEmail.trim() || share.isPending} onClick={() => { if (filterId !== null) share.mutate({ filterId, recipientEmail: recipientEmail.trim() }); }}>{share.isPending ? <Loader2 className="spin" size={14} /> : <Share2 size={14} />} Send invite</button></div>{namedShares.length > 0 && <div className="family-share-list">{namedShares.map((shareItem) => <span className={`family-share-status ${shareItem.status}`} key={shareItem.shareId}><strong>{shareItem.filterName}</strong> · {shareItem.status} for {shareItem.recipientName ?? shareItem.recipientEmail ?? "family account"}<button type="button" aria-label={`Revoke ${shareItem.filterName} ${shareItem.status} access`} disabled={revoke.isPending} onClick={() => revoke.mutate({ shareId: shareItem.shareId })}><X size={12} /></button></span>)}</div>}{activeInvitations.length > 0 && <div className="family-invitations"><small><MailCheck size={12} /> Approval needed</small>{activeInvitations.map((invite) => <div key={invite.shareId}><span><strong>{invite.filter.name}</strong><em>from {invite.ownerName ?? invite.ownerEmail ?? "family"}</em></span><button type="button" disabled={respond.isPending} onClick={() => respond.mutate({ shareId: invite.shareId, decision: "accepted" })}><Check size={12} />Accept</button><button type="button" disabled={respond.isPending} onClick={() => respond.mutate({ shareId: invite.shareId, decision: "declined" })}><X size={12} />Decline</button></div>)}</div>}{received.length > 0 && <div className="family-received"><small>Accepted family filters</small>{received.map((item) => <button key={item.shareId} type="button" onClick={() => onApply(item.filter)}>{item.filter.name} <span>from {item.ownerName ?? item.ownerEmail ?? "family"}</span></button>)}</div>}</section>;
}
