import type { SavedVerificationHistoryFilter, SharedVerificationHistoryFilter, VerificationHistoryFilterShareRecipient } from "@shared/verificationHistoryFilters";
import { trpc } from "@/lib/trpc";
import { Loader2, Share2, UsersRound, X } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import "./FamilyFilterShare.css";

export function FamilyFilterShare({ filters, shares, received, onApply }: { filters: SavedVerificationHistoryFilter[]; shares: VerificationHistoryFilterShareRecipient[]; received: SharedVerificationHistoryFilter[]; onApply: (filter: SavedVerificationHistoryFilter | SharedVerificationHistoryFilter["filter"]) => void }) {
  const utils = trpc.useUtils(); const [recipientEmail, setRecipientEmail] = useState(""); const [filterId, setFilterId] = useState<number | null>(filters[0]?.id ?? null);
  const namedShares = useMemo(() => shares.map((share) => ({ ...share, filterName: filters.find((filter) => filter.id === share.savedFilterId)?.name ?? "Deleted filter" })), [filters, shares]);
  const share = trpc.documents.historyFilters.share.useMutation({ onSuccess: async () => { setRecipientEmail(""); await utils.documents.historyFilters.list.invalidate(); toast.success("Family filter access updated."); }, onError: (error) => toast.error(error.message || "This filter could not be shared.") });
  const revoke = trpc.documents.historyFilters.revokeShare.useMutation({ onSuccess: () => utils.documents.historyFilters.list.invalidate(), onError: () => toast.error("Family access could not be revoked.") });
  return <section className="family-filter-share"><div><span className="desk-kicker"><UsersRound size={14} /> FAMILY FILTERS</span><p>Share only a saved search’s criteria—not documents, history events, or application data.</p></div><div className="family-share-form"><select value={filterId ?? ""} onChange={(event) => setFilterId(Number(event.target.value))} aria-label="Saved filter to share" disabled={!filters.length}><option value="" disabled>Select a saved filter</option>{filters.map((filter) => <option key={filter.id} value={filter.id}>{filter.name}</option>)}</select><input type="email" value={recipientEmail} placeholder="Family account email" aria-label="Family account email" onChange={(event) => setRecipientEmail(event.target.value)} /><button type="button" className="desk-outline" disabled={!filterId || !recipientEmail.trim() || share.isPending} onClick={() => { if (filterId !== null) share.mutate({ filterId, recipientEmail: recipientEmail.trim() }); }}>{share.isPending ? <Loader2 className="spin" size={14} /> : <Share2 size={14} />} Share filter</button></div>{namedShares.length > 0 && <div className="family-share-list">{namedShares.map((shareItem) => <span key={shareItem.shareId}><strong>{shareItem.filterName}</strong> with {shareItem.recipientName ?? shareItem.recipientEmail ?? "family account"}<button type="button" aria-label={`Revoke ${shareItem.filterName} access`} disabled={revoke.isPending} onClick={() => revoke.mutate({ shareId: shareItem.shareId })}><X size={12} /></button></span>)}</div>}{received.length > 0 && <div className="family-received"><small>Shared with you</small>{received.map((item) => <button key={item.shareId} type="button" onClick={() => onApply(item.filter)}>{item.filter.name} <span>from {item.ownerName ?? item.ownerEmail ?? "family"}</span></button>)}</div>}</section>;
}
