import { CalendarDays, ChevronLeft, ChevronRight, Download, Printer } from "lucide-react";
import { useMemo, useState } from "react";
import type { Scheme } from "@/lib/schemes";
import { buildOfflineSavedDeadlineCalendar, getOfflineDeadlineTiming } from "@/lib/offlineSavedDeadlineCalendar";
import { createOfflineSavedDeadlineCalendarPrintHtml } from "@/lib/offlineSavedDeadlineCalendarPrint";
import { createOfflineSavedDeadlineCalendarCsv } from "@/lib/offlineSavedDeadlineCalendarCsv";
import { downloadTextFile } from "@/lib/schemeExports";

type Language = "en" | "hi";
const weekdays = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

export function OfflineSavedDeadlineCalendar({ schemes, language, onOpen = scheme => { window.dispatchEvent(new CustomEvent<Scheme>("scheme-sathi-open-offline-saved", { detail: scheme })); } }: { schemes: Scheme[]; language: Language; onOpen?: (scheme: Scheme) => void }) {
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1));
  const [category, setCategory] = useState("all");
  const categories = useMemo(() => Array.from(new Set(schemes.map(scheme => scheme.category))).sort(), [schemes]);
  const categorySchemes = useMemo(() => category === "all" ? schemes : schemes.filter(scheme => scheme.category === category), [schemes, category]);
  const days = useMemo(() => buildOfflineSavedDeadlineCalendar(categorySchemes, month), [categorySchemes, month]);
  const formatter = new Intl.DateTimeFormat(language === "hi" ? "hi-IN" : "en-IN", { month: "long", year: "numeric" });
  const isHindi = language === "hi";
  const categoryLabel = category === "all" ? (isHindi ? "सभी श्रेणियाँ" : "All categories") : (isHindi ? schemes.find(scheme => scheme.category === category)?.categoryHindi ?? category : category);
  const monthKey = `${month.getFullYear()}-${String(month.getMonth() + 1).padStart(2, "0")}`;
  const printCalendar = () => { const printWindow = window.open("", "_blank"); if (!printWindow) return; printWindow.document.write(createOfflineSavedDeadlineCalendarPrintHtml({ schemes: categorySchemes, month, language, categoryLabel })); printWindow.document.close(); printWindow.focus(); printWindow.print(); };
  const exportCalendarCsv = () => downloadTextFile(createOfflineSavedDeadlineCalendarCsv({ schemes: categorySchemes, month, language }), `scheme-sathi-deadlines-${monthKey}-${category === "all" ? "all-categories" : category.toLocaleLowerCase().replace(/[^a-z0-9]+/g, "-")}.csv`, "text/csv;charset=utf-8");
  return <section className="offline-deadline-calendar" aria-label={isHindi ? "सहेजी योजनाओं की समयसीमा कैलेंडर" : "Saved scheme deadline calendar"}><header><div><p><CalendarDays size={14} /> {isHindi ? "समयसीमा कैलेंडर" : "DEADLINE CALENDAR"}</p><h2>{formatter.format(month)}</h2></div><div className="offline-calendar-nav"><button type="button" onClick={() => setMonth(current => new Date(current.getFullYear(), current.getMonth() - 1, 1))} aria-label={isHindi ? "पिछला महीना" : "Previous month"}><ChevronLeft size={17} /></button><button type="button" onClick={() => setMonth(current => new Date(current.getFullYear(), current.getMonth() + 1, 1))} aria-label={isHindi ? "अगला महीना" : "Next month"}><ChevronRight size={17} /></button></div></header><div className="offline-calendar-toolbar"><label className="offline-calendar-category"><span>{isHindi ? "श्रेणी फ़िल्टर" : "Category filter"}</span><select value={category} onChange={event => setCategory(event.target.value)}><option value="all">{isHindi ? "सभी श्रेणियाँ" : "All categories"}</option>{categories.map(item => <option key={item} value={item}>{isHindi ? schemes.find(scheme => scheme.category === item)?.categoryHindi ?? item : item}</option>)}</select></label><div className="offline-calendar-actions"><button type="button" className="offline-calendar-csv" onClick={exportCalendarCsv}><Download size={14} />{isHindi ? "CSV एक्सपोर्ट" : "Export CSV"}</button><button type="button" className="offline-calendar-print" onClick={printCalendar}><Printer size={14} />{isHindi ? "प्रिंट / PDF" : "Print / PDF"}</button></div></div><div className="offline-calendar-legend" aria-label={isHindi ? "समयसीमा रंग संकेत" : "Deadline color legend"}><span className="urgent"><i />{isHindi ? "7 दिन के भीतर" : "Within 7 days"}</span><span className="soon"><i />{isHindi ? "8–30 दिन" : "8–30 days"}</span><span className="later"><i />{isHindi ? "30 दिन से बाद" : "After 30 days"}</span></div><div className="offline-calendar-weekdays">{weekdays.map(day => <span key={day}>{day}</span>)}</div><div className="offline-calendar-grid">{days.map(({ date, schemes: dueSchemes, isCurrentMonth }) => <div key={date.toISOString()} className={`offline-calendar-day ${isCurrentMonth ? "" : "muted"} ${dueSchemes.length ? "has-deadline" : ""}`}><time dateTime={date.toISOString().slice(0, 10)}>{date.getDate()}</time>{dueSchemes.slice(0, 2).map(scheme => <button type="button" className={`deadline-${getOfflineDeadlineTiming(scheme.applicationDeadline!)}`} key={scheme.id} onClick={() => onOpen(scheme)} title={isHindi ? scheme.nameHindi : scheme.name}>{isHindi ? scheme.nameHindi : scheme.name}</button>)}{dueSchemes.length > 2 && <span>+{dueSchemes.length - 2}</span>}</div>)}</div></section>;
}
