import { trpc } from "@/lib/trpc";
import { AlertTriangle, BarChart3, CalendarClock, ClipboardList, Loader2, TimerReset } from "lucide-react";
import "./ReviewManagement.css";

const dateFormat = new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", hour: "numeric", minute: "2-digit" });

export function ReviewerWorkloadDashboard() {
  const workload = trpc.documents.reviewers.workload.useQuery(undefined, { retry: false });
  const summary = workload.data?.summary;
  const assignments = workload.data?.assignments ?? [];
  return <section className="review-management-card workload-dashboard"><header><div><span className="desk-kicker"><BarChart3 size={14} /> MY REVIEW WORKLOAD</span><h2>See what needs your review.</h2><p>Counts use only active assignments. Overdue and due-soon labels are calculated from each review deadline in your local time.</p></div></header>{workload.isLoading ? <div className="review-management-loading"><Loader2 className="spin" size={15} />Loading review workload…</div> : <><div className="workload-stat-grid"><article><ClipboardList size={16} /><strong>{summary?.active ?? 0}</strong><span>active</span></article><article><TimerReset size={16} /><strong>{summary?.inReview ?? 0}</strong><span>in review</span></article><article><CalendarClock size={16} /><strong>{summary?.dueSoon ?? 0}</strong><span>due within 48h</span></article><article className={(summary?.overdue ?? 0) > 0 ? "urgent" : ""}><AlertTriangle size={16} /><strong>{summary?.overdue ?? 0}</strong><span>overdue</span></article><article className={(summary?.escalated ?? 0) > 0 ? "escalated" : ""}><AlertTriangle size={16} /><strong>{summary?.escalated ?? 0}</strong><span>escalated</span></article></div><div className="workload-list">{!assignments.filter((assignment) => assignment.status === "assigned" || assignment.status === "inReview").length && <small>There are no active reviews assigned to you.</small>}{assignments.filter((assignment) => assignment.status === "assigned" || assignment.status === "inReview").map((assignment) => <article key={assignment.id}><div><strong>{assignment.documentName}</strong><small>{assignment.schemeName} · Owner: {assignment.ownerName}</small></div><span className={assignment.dueAt && assignment.dueAt < Date.now() ? "overdue" : ""}>{assignment.dueAt ? `Due ${dateFormat.format(new Date(assignment.dueAt))}` : "No due date"}</span><b className={`review-status ${assignment.status}`}>{assignment.status === "inReview" ? "In review" : "Assigned"}</b>{assignment.escalationState === "escalated" && <em>Escalated</em>}</article>)}</div></>}</section>;
}
