import { trpc } from "@/lib/trpc";
import { AlarmClock, CalendarClock, CheckCircle2, Loader2, Save, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import "./ReviewerReminderControls.css";

const formatForInput = (timestamp: number | null | undefined) => timestamp ? new Date(timestamp - new Date().getTimezoneOffset() * 60_000).toISOString().slice(0, 16) : "";
const readableDate = (timestamp: number | null) => timestamp ? new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(timestamp)) : "Not set";

export function ReviewerDueDateManager() {
  const utils = trpc.useUtils(); const applications = trpc.applications.list.useQuery(); const preferences = trpc.documents.reviewers.preferences.get.useQuery(undefined, { retry: false }); const [documentId, setDocumentId] = useState<number | null>(null); const [assignmentId, setAssignmentId] = useState<number | null>(null); const [dueValue, setDueValue] = useState(""); const [reminderValue, setReminderValue] = useState("");
  const documents = useMemo(() => (applications.data?.applications ?? []).flatMap((application) => (application.documents ?? []).map((document) => ({ id: document.id, documentName: document.documentName, schemeName: application.scheme?.name ?? application.schemeId }))), [applications.data?.applications]);
  const assignments = trpc.documents.reviewers.list.useQuery({ documentId: documentId ?? 0 }, { enabled: documentId !== null, retry: false }); const selected = assignments.data?.assignments.find((assignment) => assignment.id === assignmentId) ?? null;
  useEffect(() => { setAssignmentId(null); setDueValue(""); setReminderValue(""); }, [documentId]);
  useEffect(() => { if (selected) { setDueValue(formatForInput(selected.dueAt)); setReminderValue(formatForInput(selected.reminderAt)); } }, [selected?.id, selected?.dueAt, selected?.reminderAt]);
  const save = trpc.documents.reviewers.dueDates.set.useMutation({ onSuccess: async (result) => { await utils.documents.reviewers.list.invalidate({ documentId: documentId ?? 0 }); if (result.deferred) toast.message("Timing saved. Automatic delivery starts after the project is published and the reminder is saved again."); else toast.success(result.scheduled ? "Due-date reminder scheduled." : "Review due date saved."); }, onError: (error) => toast.error(error.message || "The due date or reminder could not be saved.") }); const cancel = trpc.documents.reviewers.dueDates.cancel.useMutation({ onSuccess: async () => { await utils.documents.reviewers.list.invalidate({ documentId: documentId ?? 0 }); setReminderValue(""); toast.message("Due-date reminder cancelled."); }, onError: (error) => toast.error(error.message || "The reminder could not be cancelled.") });
  const setDefaultLead = () => { const due = new Date(dueValue).getTime(); const hours = preferences.data?.preferences.defaultReminderLeadHours ?? 24; if (!due) return; setReminderValue(formatForInput(due - hours * 60 * 60 * 1000)); };
  const saveDueDate = () => { if (!assignmentId) return; const dueAt = dueValue ? new Date(dueValue).getTime() : null; const reminderAt = reminderValue ? new Date(reminderValue).getTime() : null; save.mutate({ assignmentId, dueAt, reminderAt }); };
  return <section className="reviewer-settings-card reviewer-due-card"><header><span className="desk-kicker"><CalendarClock size={14} /> OWNER REVIEW TIMING</span><h2>Set a clear review deadline.</h2><p>The owner controls due dates; the assigned reviewer controls whether they receive in-app reminders.</p></header><div className="reviewer-due-grid"><label>Uploaded document<select value={documentId ?? ""} onChange={(event) => setDocumentId(event.target.value ? Number(event.target.value) : null)}><option value="">Choose a document</option>{documents.map((document) => <option value={document.id} key={document.id}>{document.schemeName} · {document.documentName}</option>)}</select></label><label>Assigned reviewer<select value={assignmentId ?? ""} disabled={!documentId || assignments.isLoading} onChange={(event) => setAssignmentId(event.target.value ? Number(event.target.value) : null)}><option value="">Choose an active reviewer</option>{assignments.data?.assignments.filter((assignment) => assignment.status !== "completed" && assignment.status !== "revoked").map((assignment) => <option value={assignment.id} key={assignment.id}>{assignment.reviewerName} · {assignment.status === "inReview" ? "in review" : "assigned"}</option>)}</select></label>{selected && <><label>Review due date<input type="datetime-local" min={formatForInput(Date.now() + 60_000)} value={dueValue} onChange={(event) => setDueValue(event.target.value)} /></label><label>One-time reminder<input type="datetime-local" min={formatForInput(Date.now() + 60_000)} value={reminderValue} onChange={(event) => setReminderValue(event.target.value)} /></label><div className="reviewer-due-actions"><button className="desk-outline" type="button" disabled={!dueValue} onClick={setDefaultLead}><AlarmClock size={14} />Use reviewer lead time</button><button className="desk-primary" type="button" disabled={!dueValue || save.isPending} onClick={saveDueDate}>{save.isPending ? <Loader2 className="spin" size={14} /> : <Save size={14} />}Save timing</button>{selected.reminderStatus === "scheduled" && <button className="reviewer-danger" type="button" disabled={cancel.isPending} onClick={() => cancel.mutate({ assignmentId: selected.id })}><X size={14} />Cancel reminder</button>}</div><div className="reviewer-due-status"><CheckCircle2 size={14} /><span>Due: <strong>{readableDate(selected.dueAt)}</strong> · Reminder: <strong>{selected.reminderStatus === "scheduled" ? readableDate(selected.reminderAt) : selected.reminderStatus}</strong></span></div></>}</div></section>;
}
