import { trpc } from "@/lib/trpc";
import { BellRing, Loader2, Save, Settings2 } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import "./ReviewerReminderControls.css";

export function ReviewerAlertPreferences() {
  const utils = trpc.useUtils();
  const preferences = trpc.documents.reviewers.preferences.get.useQuery(undefined, { retry: false });
  const [assignmentAlertsEnabled, setAssignmentAlertsEnabled] = useState(true); const [dueDateRemindersEnabled, setDueDateRemindersEnabled] = useState(true); const [defaultReminderLeadHours, setDefaultReminderLeadHours] = useState(24); const [maxActiveAssignments, setMaxActiveAssignments] = useState(5);
  useEffect(() => { if (preferences.data?.preferences) { setAssignmentAlertsEnabled(preferences.data.preferences.assignmentAlertsEnabled); setDueDateRemindersEnabled(preferences.data.preferences.dueDateRemindersEnabled); setDefaultReminderLeadHours(preferences.data.preferences.defaultReminderLeadHours); setMaxActiveAssignments(preferences.data.preferences.maxActiveAssignments); } }, [preferences.data?.preferences]);
  const save = trpc.documents.reviewers.preferences.save.useMutation({ onSuccess: async () => { await Promise.all([utils.documents.reviewers.preferences.get.invalidate(), utils.documents.reviewers.notifications.invalidate()]); toast.success("Reviewer alert preferences saved."); }, onError: (error) => toast.error(error.message || "Preferences could not be saved.") });
  const submit = () => save.mutate({ assignmentAlertsEnabled, dueDateRemindersEnabled, defaultReminderLeadHours: Math.max(1, Math.min(168, Math.round(defaultReminderLeadHours || 24))), maxActiveAssignments: Math.max(1, Math.min(50, Math.round(maxActiveAssignments || 5))) });
  return <section className="reviewer-settings-card"><header><span className="desk-kicker"><Settings2 size={14} /> REVIEWER SETTINGS</span><h2>Choose the alerts you receive.</h2><p>These choices belong only to your account. They never change another person’s review settings.</p></header>{preferences.isLoading ? <div className="reviewer-controls-loading"><Loader2 className="spin" size={15} />Loading preferences…</div> : <div className="reviewer-preference-grid"><label className="reviewer-toggle"><input type="checkbox" checked={assignmentAlertsEnabled} onChange={(event) => setAssignmentAlertsEnabled(event.target.checked)} /><span><strong>New assignment alerts</strong><small>Show an in-app alert whenever an owner assigns or reassigns you.</small></span></label><label className="reviewer-toggle"><input type="checkbox" checked={dueDateRemindersEnabled} onChange={(event) => setDueDateRemindersEnabled(event.target.checked)} /><span><strong>Due-date reminders</strong><small>Allow one in-app reminder before an active assigned review is due.</small></span></label><label className="reviewer-lead-time"><BellRing size={14} /><span>Default reminder lead time<input type="number" min="1" max="168" value={defaultReminderLeadHours} onChange={(event) => setDefaultReminderLeadHours(Number(event.target.value))} />hours before due</span></label><label className="reviewer-lead-time"><Settings2 size={14} /><span>Maximum active reviews<input type="number" min="1" max="50" value={maxActiveAssignments} onChange={(event) => setMaxActiveAssignments(Number(event.target.value))} />documents at once</span></label><button className="desk-outline" disabled={save.isPending} onClick={submit}>{save.isPending ? <Loader2 className="spin" size={14} /> : <Save size={14} />}Save reviewer settings</button></div>}</section>;
}
