import { Check, ExternalLink, X } from "lucide-react";
import type { Scheme } from "@/lib/schemes";

type Language = "en" | "hi";
const text = (language: Language, english: string, hindi: string) => language === "hi" ? hindi : english;
export function SchemeComparisonModal({ schemes, language, onClose, onRemove }: { schemes: (Scheme & { score: number; factors: string[] })[]; language: Language; onClose: () => void; onRemove: (id: string) => void }) {
  const rows = [
    { label: text(language, "Match score", "मिलान स्कोर"), value: (scheme: Scheme & { score: number }) => `${scheme.score}/100` },
    { label: text(language, "Benefit", "लाभ"), value: (scheme: Scheme) => text(language, scheme.benefits, scheme.benefitsHindi) },
    { label: text(language, "Key eligibility", "मुख्य पात्रता"), value: (scheme: Scheme) => [scheme.eligibility.age_min !== undefined ? `${text(language, "Age", "आयु")}: ${scheme.eligibility.age_min}${scheme.eligibility.age_max ? `–${scheme.eligibility.age_max}` : "+"}` : null, scheme.eligibility.income_max ? `${text(language, "Income up to", "आय सीमा")}: ₹${scheme.eligibility.income_max.toLocaleString("en-IN")}` : null, scheme.eligibility.states !== "all" && scheme.eligibility.states ? scheme.eligibility.states.join(", ") : text(language, "All India", "पूरे भारत में")].filter(Boolean).join(" · ") },
    { label: text(language, "Documents", "दस्तावेज़"), value: (scheme: Scheme) => (language === "hi" ? scheme.documentsHindi : scheme.documents).join(" · ") },
    { label: text(language, "Application steps", "आवेदन के चरण"), value: (scheme: Scheme) => (language === "hi" ? scheme.stepsHindi : scheme.steps).map((step, index) => `${index + 1}. ${step}`).join("\n") },
  ];
  return <div className="comparison-backdrop" role="presentation" onClick={onClose}><section className="comparison-modal" role="dialog" aria-modal="true" aria-label={text(language, "Compare schemes", "योजनाओं की तुलना")} onClick={(event) => event.stopPropagation()}><header><div><span className="section-kicker">{text(language, "Side-by-side", "साथ-साथ")}</span><h2>{text(language, "Compare your selected schemes", "चुनी हुई योजनाओं की तुलना करें")}</h2></div><button onClick={onClose} aria-label={text(language, "Close comparison", "तुलना बंद करें")}><X size={20} /></button></header><div className="comparison-table-wrap"><table><thead><tr><th>{text(language, "What to compare", "तुलना का बिंदु")}</th>{schemes.map((scheme) => <th key={scheme.id}><button onClick={() => onRemove(scheme.id)} aria-label={text(language, `Remove ${scheme.name} from comparison`, `${scheme.nameHindi} को तुलना से हटाएँ`)}><X size={13} /></button><strong>{text(language, scheme.name, scheme.nameHindi)}</strong></th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.label}><th>{row.label}</th>{schemes.map((scheme) => <td key={scheme.id}>{row.value(scheme)}</td>)}</tr>)}<tr><th>{text(language, "Official portal", "आधिकारिक पोर्टल")}</th>{schemes.map((scheme) => <td key={scheme.id}><a href={scheme.portalUrl} target="_blank" rel="noreferrer"><ExternalLink size={13} />{text(language, "Open portal", "पोर्टल खोलें")}</a></td>)}</tr></tbody></table></div><footer><Check size={15} />{text(language, "Compare options, then verify the latest details on each official portal.", "विकल्पों की तुलना करें, फिर हर आधिकारिक पोर्टल पर नवीनतम जानकारी जाँचें।")}</footer></section></div>;
}
